### ISSUE TITLE
[perbaikan][ghina] tabel perizinan, menambahkan satu field jumlah_hari_pengajuan

### ISSUE THREAD

**Issue by Allmerr** [ghinaat/Sikil#78]
tambahkan pada table perizinan field jumlah_hari_pengajuan

alasan:
terjadi masalah ketika user mengajukan perizinan, yaitu ketika user menginput tanggal awal dan tanggal akhir, tidak ada validasi apakah masuk tanggal merah dan tanggal akhir. ini menjadi suatu bug ketika user mengajukan cuti yang mana sistem membutuhkan field jatah cuti di table cuti sebagai patokan jatah cutinya.

**Comment by Allmerr** [comment]
mohon berikan logika solusinya sebelum melakukan code

**Comment by ghinaat** [comment]
jadi misalnya kayak dari jumat sabtu minggu senin, sabtu minggu nya otomatis ga keitung cuti gitu kan pin

**Comment by Allmerr** [comment]
betul banget gin
