### ISSUE TITLE
[perbaikan][ghina] hal kelola perizinan (kadiv/atasan,ppk), perizinan kadiv masih belum bisa tersimpan

### ISSUE THREAD

**Issue by Allmerr** [ghinaat/Sikil#81]
data masih belum tersimpan ke db

**Comment by ghinaat** [comment]
ini maksudnya waktu apa ya mas

**Comment by Allmerr** [comment]
tadi saya coba pengajuan perizinan di kelola perizinan, setelah ngelakuin data tidak tersimpan ke dalam database

**Comment by ghinaat** [comment]
tapi pengajuan di kelola perizinan kan cuman admin doang yang bisa

**Comment by Allmerr** [comment]
Kelola perizinan di user management bisa akses oleh kadiv atau ppk
